export const FETCH_IMAGE_INFO_SUCCESS = 'FETCH_IMAGE_INFO_SUCCESS';
export const FETCH_IMAGE_INFO_REQ = 'FETCH_IMAGE_INFO_REQ';
export const CLEAR_IMAGE_INFO_REQ = 'CLEAR_IMAGE_INFO_REQ';
export const CLEAR_IMAGE_INFO = 'CLEAR_IMAGE_INFO';